import * as stylex from "@stylexjs/stylex";
const mobile = "@media (max-width: 48rem)";
const narrow = "@media (max-width: 68rem)";

/** Responsive footer keeps contact information and navigation usable on touch screens. */
export const styles = stylex.create({
  footer: {
    position: "relative",
    overflow: "hidden",
    paddingBlock: "clamp(4rem, 8vw, 8.5rem)",
    paddingInline: 24,
    backgroundColor: "#000098",
    color: "white",
    fontFamily: "var(--font-plus-jakarta-sans), Arial, sans-serif",
  },
  backdrop: {
    position: "absolute",
    top: "35%",
    left: "51%",
    width: "max(65%, 32rem)",
    height: "auto",
    pointerEvents: "none",
  },
  inner: { position: "relative", maxWidth: 1120, marginInline: "auto" },
  heading: {
    marginTop: 0,
    marginBottom: "clamp(3rem, 9vw, 8.5rem)",
    fontSize: "clamp(2.5rem, 6.65vw, 6rem)",
    fontWeight: 400,
    lineHeight: 1.2,
    letterSpacing: "-0.04em",
    textWrap: "balance",
  },
  contactGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "1.65fr .8fr 1fr",
      [narrow]: "1.3fr 1fr",
      [mobile]: "minmax(0, 1fr)",
    },
    columnGap: 48,
    rowGap: 36,
  },
  description: {
    margin: 0,
    maxWidth: 444,
    fontSize: "clamp(1.5rem, 2.1vw, 1.875rem)",
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: "-0.04em",
    gridRow: { default: "auto", [narrow]: "span 2", [mobile]: "auto" },
  },
  contactTitle: {
    marginTop: 0,
    marginBottom: { default: 32, [mobile]: 16 },
    fontSize: 20,
    fontWeight: 700,
    lineHeight: 1.5,
  },
  address: { fontStyle: "normal", fontSize: 18, lineHeight: 1.5 },
  contactLinks: { display: "flex", flexDirection: "column", gap: 12 },
  link: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    minHeight: 44,
    color: "inherit",
    fontSize: 18,
    lineHeight: 1.5,
    textDecoration: "underline",
    textUnderlineOffset: 4,
    borderRadius: 4,
  },
  email: { overflowWrap: "anywhere", minWidth: 0 },
  bottom: {
    marginTop: "clamp(3.5rem, 10vw, 10rem)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    columnGap: 40,
    rowGap: 32,
  },
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: 20,
    color: "white",
    fontSize: "clamp(2rem, 3.2vw, 2.875rem)",
    textDecoration: "none",
    borderRadius: 4,
  },
  copyright: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.5,
    order: { default: 0, [mobile]: 1 },
    width: { default: "auto", [mobile]: "100%" },
  },
  socials: { display: "flex", gap: 16 },
  social: {
    display: "grid",
    placeItems: "center",
    width: 48,
    height: 48,
    borderWidth: 0,
    borderRadius: 12,
    backgroundColor: "#ffffff1a",
    opacity: 0.65,
    cursor: "not-allowed",
  },
});
