import * as stylex from "@stylexjs/stylex";

const mobile = "@media (max-width: 48rem)";
const tablet = "@media (min-width: 48.001rem) and (max-width: 68rem)";

/** Figma solution layouts, with content-driven heights for text resizing. */
export const styles = stylex.create({
  section: {
    paddingBlock: { default: 84, [mobile]: 51 },
    paddingInline: 24,
    color: "#181d27",
    fontFamily: "var(--font-plus-jakarta-sans), Arial, sans-serif",
  },
  header: { maxWidth: { default: 928, [mobile]: 345 }, marginInline: "auto", textAlign: "center" },
  title: {
    margin: 0,
    color: "#000098",
    fontSize: { default: 48, [mobile]: 40 },
    fontWeight: { default: 800, [mobile]: 600 },
    lineHeight: 1.25,
    letterSpacing: { default: 0, [mobile]: "-0.04em" },
  },
  intro: {
    marginTop: 18,
    marginBottom: 0,
    fontSize: { default: 24, [mobile]: 16 },
    lineHeight: { default: 1.25, [mobile]: 1.5 },
  },
  content: {
    maxWidth: { default: 1120, [mobile]: 345 },
    marginInline: "auto",
    marginTop: { default: 72, [mobile]: 48 },
  },
  topGrid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", [mobile]: "minmax(0, 1fr)" },
    gap: 32,
  },
  process: {
    backgroundColor: "#fff",
    borderRadius: 24,
    boxShadow: "0 16px 64px #0000981a",
    paddingBlock: 31,
    paddingInline: 32,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 16,
    minHeight: 356,
  },
  cardHeading: { margin: 0, fontSize: 24, fontWeight: 700, lineHeight: 1.5 },
  steps: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  step: { display: "grid", gridTemplateColumns: "32px minmax(0, 1fr)", gap: 16 },
  number: {
    display: "grid",
    placeItems: "center",
    width: 32,
    height: 32,
    borderRadius: "50%",
    backgroundColor: "#000098",
    color: "white",
    fontSize: 14,
    fontWeight: 700,
  },
  stepTitle: { margin: 0, fontSize: 16, lineHeight: 1.5, fontWeight: 600 },
  stepCopy: { marginTop: 4, marginBottom: 0, fontSize: 14, lineHeight: "20px" },
  summary: {
    paddingBlock: 29,
    paddingInline: { default: 33, [tablet]: 24 },
    minHeight: 356,
    borderRadius: 24,
    backgroundColor: "#2e2eab",
    color: "white",
    textAlign: "center",
    boxShadow: "0 16px 64px #0000981a",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 19,
  },
  summaryHeading: { margin: 0, fontSize: 24, fontWeight: 700, lineHeight: "40px" },
  summaryIntro: {
    marginTop: 6,
    marginBottom: 0,
    fontSize: { default: 18, [mobile]: 16 },
    lineHeight: "28px",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", [mobile]: "minmax(0, 1fr)" },
    columnGap: { default: 32, [tablet]: 16 },
    rowGap: 18,
    width: "100%",
    maxWidth: 416,
    margin: 0,
  },
  summaryTile: {
    backgroundColor: "#ffffff1a",
    borderRadius: 12,
    minHeight: 92,
    paddingBlock: 5,
    paddingInline: 10,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  aspectName: { fontSize: { default: 24, [tablet]: 20 }, lineHeight: "32px", fontWeight: 700 },
  aspectSummary: {
    margin: 0,
    fontSize: 14,
    lineHeight: "20px",
    maxWidth: { default: 145, [mobile]: "none" },
  },
  green: { color: "#32d583" },
  yellow: { color: "#fec84b" },
  blue: { color: "#7cd4fd" },
  purple: { color: "#d3c5f9" },
  details: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      [tablet]: "repeat(2, minmax(0, 1fr))",
      [mobile]: "repeat(2, minmax(0, 1fr))",
    },
    gap: { default: 32, [mobile]: "32px 25px" },
    marginTop: 32,
  },
  detail: { textAlign: "center", minWidth: 0 },
  illustration: {
    height: { default: 250, [mobile]: "auto" },
    aspectRatio: { default: "auto", [mobile]: "256 / 250" },
    display: "grid",
    placeItems: "center",
    borderRadius: { default: 12, [mobile]: 7.5 },
    boxShadow: "0 16px 64px #0000981a",
  },
  art: { position: "relative", overflow: "hidden", maxWidth: "75%" },
  personalityArt: { width: { default: 139, [mobile]: 87 }, aspectRatio: "139 / 149" },
  skillsArt: { width: { default: 132, [mobile]: 82.5 }, aspectRatio: "132 / 152" },
  genderArt: { width: { default: 159, [mobile]: 99.4 }, aspectRatio: "159 / 118" },
  image: { display: "block", width: "100%", height: "100%" },
  personalityCrop: {
    position: "absolute",
    left: "-17.9%",
    top: "0.34%",
    width: "117.81%",
    maxWidth: "none",
  },
  preferenceArt: {
    position: "relative",
    width: { default: 151, [mobile]: 94.4 },
    aspectRatio: "151 / 148.24",
  },
  preferenceBox: {
    position: "absolute",
    left: "8.46%",
    top: "9.26%",
    width: "81.31%",
    height: "81.79%",
  },
  preferenceCheck: {
    position: "absolute",
    left: "23.76%",
    top: "9.53%",
    width: "66.36%",
    height: "62.04%",
  },
  personalityTile: { backgroundColor: "#d1fadf" },
  skillsTile: { backgroundColor: "#fef0c7" },
  genderTile: { backgroundColor: "#b9e6fe" },
  preferenceTile: { backgroundColor: "#d9d6fe" },
  personalityText: { color: "#027a48" },
  skillsText: { color: "#b54708" },
  genderText: { color: "#026aa2" },
  preferenceText: { color: "#5925dc" },
  detailTitle: {
    marginTop: { default: 16, [mobile]: 10 },
    marginBottom: 0,
    fontSize: { default: 24, [mobile]: 16 },
    fontWeight: 700,
    lineHeight: { default: "36px", [mobile]: "22.5px" },
  },
  detailCopy: {
    marginTop: { default: 9, [mobile]: 5.625 },
    marginBottom: 0,
    fontSize: { default: 14, [mobile]: 12 },
    lineHeight: { default: "20px", [mobile]: "18px" },
  },
});
